import type { Metadata } from "next";
import localFont from "next/font/local";
import '../styles/globals.css';
import { poppins } from "@/app/Font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
